// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcPendlePhase13aDeploy} from "./BcPendlePhase13aDeploy.sol";

/// @notice Phase 13a: Pendle seed — factories, AllAction router, one ERC20 SY, PT/YT + market + oracle.
/// @dev Uses BcPendlePhase13aDeploy (shared with hermetic/fork tests). No live BC until §0 gate.
contract Script_BC_Phase13a_Pendle is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-pendle.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-pendle.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-13a-pendle.latest.json";
    string internal constant MANIFEST_RUNTIME_GREENFIELD =
        "script/output/battlechain-sepolia/greenfield-phase13a-pendle.latest.json";

    address public phase13aDeployer;
    address public yieldContractFactory;
    address public marketFactory;
    address public router;
    address public poolDeployHelper;
    address public pyLpOracle;
    address public sy;
    address public pt;
    address public yt;
    address public market;
    address public underlying;
    uint32 public expiry;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 13a Pendle";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        // Phase 1 CREATE3 may still be zero pre-live; only bind when set.
        // Seed deploys via helper CREATE (not CREATE3) — same as Phase 9 Liquity.
        if (BC_TESTNET.CREATE3_FACTORY != address(0)) {
            _bindPhase1FromConstants();
        }

        address wethAddr = weth != address(0) ? weth : BC_TESTNET.WETH;
        require(wethAddr != address(0) && wethAddr.code.length > 0, "13a: BC WETH required for seed SY");

        BcPendlePhase13aDeploy helper = new BcPendlePhase13aDeploy();
        phase13aDeployer = address(helper);
        BcPendlePhase13aDeploy.DeployResult memory r = helper.deploySeed(deployer, wethAddr);
        _store(r);

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("phase13aDeployer", phase13aDeployer);
        console2.log("router", router);
        console2.log("yieldContractFactory", yieldContractFactory);
        console2.log("marketFactory", marketFactory);
        console2.log("sy", sy);
        console2.log("pt", pt);
        console2.log("yt", yt);
        console2.log("market", market);
        console2.log("pyLpOracle", pyLpOracle);
        console2.log("underlying (WETH)", underlying);
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    /// @notice In-process deploy for FullStack / tests (no broadcast).
    function deployForFullStack(address treasury, address underlying_)
        external
        returns (BcPendlePhase13aDeploy.DeployResult memory r)
    {
        require(treasury != address(0), "13a: treasury zero");
        BcPendlePhase13aDeploy helper = new BcPendlePhase13aDeploy();
        phase13aDeployer = address(helper);
        r = helper.deploySeed(treasury, underlying_);
        _store(r);
        _writeManifest(treasury);
    }

    function _store(BcPendlePhase13aDeploy.DeployResult memory r) internal {
        yieldContractFactory = r.yieldContractFactory;
        marketFactory = r.marketFactory;
        router = r.router;
        poolDeployHelper = r.poolDeployHelper;
        pyLpOracle = r.pyLpOracle;
        sy = r.sy;
        pt = r.pt;
        yt = r.yt;
        market = r.market;
        underlying = r.underlying;
        expiry = r.expiry;
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_GREENFIELD, deployer);

        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase13a_Pendle (greenfield) -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "phase13aDeployer", phase13aDeployer);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Router (AllAction V3 / V4)", router);
        _writeTableRow(MANIFEST_DOCS_TABLE, "YieldContractFactory", yieldContractFactory);
        _writeTableRow(MANIFEST_DOCS_TABLE, "MarketFactoryV3", marketFactory);
        _writeTableRow(MANIFEST_DOCS_TABLE, "PoolDeployHelper", poolDeployHelper);
        _writeTableRow(MANIFEST_DOCS_TABLE, "PendlePYLpOracle", pyLpOracle);
        _writeTableRow(MANIFEST_DOCS_TABLE, "SY", sy);
        _writeTableRow(MANIFEST_DOCS_TABLE, "PT", pt);
        _writeTableRow(MANIFEST_DOCS_TABLE, "YT", yt);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Market", market);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Underlying", underlying);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": "13a",');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase13a_Pendle.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, string.concat('  "phase13aDeployer": "', vm.toString(phase13aDeployer), '",'));
        vm.writeLine(path, string.concat('  "expiry": ', vm.toString(uint256(expiry)), ","));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "router", router, false);
        _writeJsonAddr(path, "yieldContractFactory", yieldContractFactory, false);
        _writeJsonAddr(path, "marketFactory", marketFactory, false);
        _writeJsonAddr(path, "poolDeployHelper", poolDeployHelper, false);
        _writeJsonAddr(path, "pyLpOracle", pyLpOracle, false);
        _writeJsonAddr(path, "sy", sy, false);
        _writeJsonAddr(path, "pt", pt, false);
        _writeJsonAddr(path, "yt", yt, false);
        _writeJsonAddr(path, "market", market, false);
        _writeJsonAddr(path, "underlying", underlying, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
