// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {IERC20} from "@crane/contracts/external/openzeppelin-contracts/token/ERC20/IERC20.sol";
import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcReliquaryPhase12Deploy} from "./BcReliquaryPhase12Deploy.sol";

/// @notice Phase 12: Reliquary + full curve set + reward funding (create-relic path).
contract Script_BC_Phase12_Reliquary is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-reliquary.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-reliquary.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-12-reliquary.latest.json";
    string internal constant MANIFEST_RUNTIME_GREENFIELD =
        "script/output/battlechain-sepolia/greenfield-phase12-reliquary.latest.json";

    address public phase12Deployer;
    address public rewardToken;
    address public poolToken;
    address public reliquary;
    address public linearCurve;
    address public linearPlateauCurve;
    address public polynomialCurve;
    uint256 public rewardFunded;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 12 Reliquary";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        if (BC_TESTNET.CREATE3_FACTORY != address(0) && BC_TESTNET.CREATE3_FACTORY != ABANDONED_CREATE3_FACTORY) {
            _bindPhase1FromConstants();
        }

        BcReliquaryPhase12Deploy helper = new BcReliquaryPhase12Deploy();
        phase12Deployer = address(helper);

        BcReliquaryPhase12Deploy.DeployResult memory r;
        address mtk = BC_TESTNET.MTK;
        address wethAddr = BC_TESTNET.WETH;
        // Prefer BC binds when funded; else hermetic mintable path.
        // bootstrap Relic NFT goes to deployer (EOA) — not the helper contract.
        if (mtk.code.length > 0 && wethAddr.code.length > 0 && IERC20(mtk).balanceOf(deployer) > 0) {
            uint256 fund = IERC20(mtk).balanceOf(deployer) / 2;
            IERC20(mtk).transfer(address(helper), fund);
            // 1 wei pool token for addPool bootstrap deposit
            if (IERC20(wethAddr).balanceOf(deployer) > 0) {
                IERC20(wethAddr).transfer(address(helper), 1);
            }
            r = helper.deployWithTokens(mtk, wethAddr, fund, deployer);
        } else {
            r = helper.deployHermetic(deployer);
        }
        _store(r);

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("phase12Deployer", phase12Deployer);
        console2.log("reliquary", reliquary);
        console2.log("linearCurve", linearCurve);
        console2.log("linearPlateauCurve", linearPlateauCurve);
        console2.log("polynomialCurve", polynomialCurve);
        console2.log("rewardFunded", rewardFunded);
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    function deployForHermetic(address bootstrapTo)
        external
        returns (BcReliquaryPhase12Deploy.DeployResult memory r)
    {
        BcReliquaryPhase12Deploy helper = new BcReliquaryPhase12Deploy();
        phase12Deployer = address(helper);
        r = helper.deployHermetic(bootstrapTo);
        _store(r);
    }

    function _store(BcReliquaryPhase12Deploy.DeployResult memory r) internal {
        reliquary = r.reliquary;
        linearCurve = r.linearCurve;
        linearPlateauCurve = r.linearPlateauCurve;
        polynomialCurve = r.polynomialCurve;
        rewardToken = r.rewardToken;
        poolToken = r.poolToken;
        rewardFunded = r.rewardFunded;
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_GREENFIELD, deployer);
        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase12_Reliquary (greenfield) -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "Reliquary", reliquary);
        _writeTableRow(MANIFEST_DOCS_TABLE, "LinearCurve", linearCurve);
        _writeTableRow(MANIFEST_DOCS_TABLE, "LinearPlateauCurve", linearPlateauCurve);
        _writeTableRow(MANIFEST_DOCS_TABLE, "PolynomialPlateauCurve", polynomialCurve);
        _writeTableRow(MANIFEST_DOCS_TABLE, "RewardToken", rewardToken);
        _writeTableRow(MANIFEST_DOCS_TABLE, "PoolToken", poolToken);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 12,');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase12_Reliquary.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, string.concat('  "rewardFunded": "', vm.toString(rewardFunded), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "reliquary", reliquary, false);
        _writeJsonAddr(path, "linearCurve", linearCurve, false);
        _writeJsonAddr(path, "linearPlateauCurve", linearPlateauCurve, false);
        _writeJsonAddr(path, "polynomialCurve", polynomialCurve, false);
        _writeJsonAddr(path, "rewardToken", rewardToken, false);
        _writeJsonAddr(path, "poolToken", poolToken, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
