// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcFraxPhase13bDeploy} from "./BcFraxPhase13bDeploy.sol";

/// @notice Phase 13b: FraxswapFactory + pair + full BAMM graph (TestBase_FraxBAMM / BAMMTest list).
/// @dev Exact contract list (BAMMTest._deployBamm):
///      1. FraxswapFactory
///      2. FraxswapPair (via factory.createPair)
///      3. FraxswapDummyRouter (BAMM router arg)
///      4. BAMMHelper
///      5. FraxswapOracle
///      6. BAMM
///      Hermetic path also deploys DummyToken pair tokens. Fork path uses BC WETH+USDC when funded.
contract Script_BC_Phase13b_Frax is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-frax.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-frax.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-13b-frax.latest.json";
    string internal constant MANIFEST_RUNTIME_GREENFIELD =
        "script/output/battlechain-sepolia/greenfield-phase13b-frax.latest.json";

    address public phase13bDeployer;
    address public fraxswapFactory;
    address public pair;
    address public token0;
    address public token1;
    address public bamm;
    address public bammHelper;
    address public fraxswapOracle;
    address public fraxswapDummyRouter;
    uint256 public pairFeeTier;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 13b Frax";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        if (BC_TESTNET.CREATE3_FACTORY != address(0)) {
            _bindPhase1FromConstants();
        }

        BcFraxPhase13bDeploy helper = new BcFraxPhase13bDeploy();
        phase13bDeployer = address(helper);

        // Prefer BC WETH+USDC pair when both have code (fork / live BC).
        // Seed liquidity only if helper is pre-funded; pair creation still succeeds without seed.
        address wethAddr = BC_TESTNET.WETH;
        address usdcAddr = BC_TESTNET.USDC;
        BcFraxPhase13bDeploy.DeployResult memory r;
        if (wethAddr.code.length > 0 && usdcAddr.code.length > 0) {
            r = helper.deployWithTokens(deployer, wethAddr, usdcAddr, 0);
        } else {
            // Hermetic-style fallback (e.g. pure Anvil without BC binds)
            r = helper.deployHermetic(deployer, 100e18);
        }
        _store(r);

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("phase13bDeployer", phase13bDeployer);
        console2.log("fraxswapFactory", fraxswapFactory);
        console2.log("pair", pair);
        console2.log("bamm", bamm);
        console2.log("bammHelper", bammHelper);
        console2.log("fraxswapOracle", fraxswapOracle);
        console2.log("fraxswapDummyRouter", fraxswapDummyRouter);
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    /// @notice In-process hermetic deploy for tests (mintable tokens + seeded pair + BAMM).
    function deployHermeticForTests(address owner)
        external
        returns (BcFraxPhase13bDeploy.DeployResult memory r)
    {
        BcFraxPhase13bDeploy helper = new BcFraxPhase13bDeploy();
        phase13bDeployer = address(helper);
        r = helper.deployHermetic(owner, 100e18);
        _store(r);
        _writeManifest(owner);
    }

    function _store(BcFraxPhase13bDeploy.DeployResult memory r) internal {
        fraxswapFactory = r.fraxswapFactory;
        pair = r.pair;
        token0 = r.token0;
        token1 = r.token1;
        bamm = r.bamm;
        bammHelper = r.bammHelper;
        fraxswapOracle = r.fraxswapOracle;
        fraxswapDummyRouter = r.fraxswapDummyRouter;
        pairFeeTier = r.pairFeeTier;
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_GREENFIELD, deployer);

        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase13b_Frax (greenfield) -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "phase13bDeployer", phase13bDeployer);
        _writeTableRow(MANIFEST_DOCS_TABLE, "FraxswapFactory", fraxswapFactory);
        _writeTableRow(MANIFEST_DOCS_TABLE, "FraxswapPair", pair);
        _writeTableRow(MANIFEST_DOCS_TABLE, "token0", token0);
        _writeTableRow(MANIFEST_DOCS_TABLE, "token1", token1);
        _writeTableRow(MANIFEST_DOCS_TABLE, "BAMM", bamm);
        _writeTableRow(MANIFEST_DOCS_TABLE, "BAMMHelper", bammHelper);
        _writeTableRow(MANIFEST_DOCS_TABLE, "FraxswapOracle", fraxswapOracle);
        _writeTableRow(MANIFEST_DOCS_TABLE, "FraxswapDummyRouter", fraxswapDummyRouter);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": "13b",');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase13b_Frax.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, string.concat('  "phase13bDeployer": "', vm.toString(phase13bDeployer), '",'));
        vm.writeLine(path, string.concat('  "pairFeeTier": ', vm.toString(pairFeeTier), ","));
        vm.writeLine(path, '  "contractList": [');
        vm.writeLine(path, '    "FraxswapFactory",');
        vm.writeLine(path, '    "FraxswapPair",');
        vm.writeLine(path, '    "FraxswapDummyRouter",');
        vm.writeLine(path, '    "BAMMHelper",');
        vm.writeLine(path, '    "FraxswapOracle",');
        vm.writeLine(path, '    "BAMM"');
        vm.writeLine(path, "  ],");
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "fraxswapFactory", fraxswapFactory, false);
        _writeJsonAddr(path, "pair", pair, false);
        _writeJsonAddr(path, "token0", token0, false);
        _writeJsonAddr(path, "token1", token1, false);
        _writeJsonAddr(path, "bamm", bamm, false);
        _writeJsonAddr(path, "bammHelper", bammHelper, false);
        _writeJsonAddr(path, "fraxswapOracle", fraxswapOracle, false);
        _writeJsonAddr(path, "fraxswapDummyRouter", fraxswapDummyRouter, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
