// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcSkyPhase10Deploy} from "./BcSkyPhase10Deploy.sol";

/// @notice Phase 10: Sky/DSS core via SkyDssFactoryService + one ilk (full manifest).
/// @dev Multi-root Safe Harbor: plain `new` graph (not CREATE3 under Phase 1). See helper NatSpec.
contract Script_BC_Phase10_Sky is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-sky.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-sky.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-10-sky.latest.json";
    string internal constant MANIFEST_RUNTIME_GREENFIELD =
        "script/output/battlechain-sepolia/greenfield-phase10-sky.latest.json";

    uint256 internal constant WAD = 10 ** 18;

    address public phase10Deployer;
    address public vat;
    address public dai;
    address public daiJoin;
    address public jug;
    address public pot;
    address public spotter;
    address public vow;
    address public dog;
    address public flapper;
    address public flopper;
    address public end;
    address public chainlog;
    address public gemJoin;
    address public gem;
    address public pip;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 10 Sky";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        if (BC_TESTNET.CREATE3_FACTORY != address(0) && BC_TESTNET.CREATE3_FACTORY != ABANDONED_CREATE3_FACTORY) {
            _bindPhase1FromConstants();
        }

        BcSkyPhase10Deploy helper = new BcSkyPhase10Deploy();
        phase10Deployer = address(helper);

        BcSkyPhase10Deploy.DeployResult memory r;
        address wethAddr = BC_TESTNET.WETH;
        if (wethAddr.code.length > 0) {
            // BC WETH gem + DSValue pip at $2000 (Chainlink is not Maker peek ABI).
            r = helper.deployWithGemAndFixedPip(BC_TESTNET.CHAIN_ID, wethAddr, 2000 * WAD);
        } else {
            r = helper.deployHermetic(block.chainid);
        }
        _store(r);

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("phase10Deployer", phase10Deployer);
        console2.log("vat", vat);
        console2.log("dai", dai);
        console2.log("flapper", flapper);
        console2.log("flopper", flopper);
        console2.log("pot", pot);
        console2.log("chainlog", chainlog);
        console2.log("gemJoin", gemJoin);
        console2.log("lineage: multi-root Safe Harbor (SkyDssFactoryService plain new, not Phase1 CREATE3)");
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    function deployForHermetic() external returns (BcSkyPhase10Deploy.DeployResult memory r) {
        BcSkyPhase10Deploy helper = new BcSkyPhase10Deploy();
        phase10Deployer = address(helper);
        r = helper.deployHermetic(block.chainid);
        _store(r);
    }

    function _store(BcSkyPhase10Deploy.DeployResult memory r) internal {
        vat = r.vat;
        dai = r.dai;
        daiJoin = r.daiJoin;
        jug = r.jug;
        pot = r.pot;
        spotter = r.spotter;
        vow = r.vow;
        dog = r.dog;
        flapper = r.flapper;
        flopper = r.flopper;
        end = r.end;
        chainlog = r.chainlog;
        gemJoin = r.gemJoin;
        gem = r.gem;
        pip = r.pip;
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_GREENFIELD, deployer);
        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase10_Sky (greenfield) -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "Vat", vat);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Dai", dai);
        _writeTableRow(MANIFEST_DOCS_TABLE, "DaiJoin", daiJoin);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Jug", jug);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Pot", pot);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Spotter", spotter);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Vow", vow);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Dog", dog);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Flapper", flapper);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Flopper", flopper);
        _writeTableRow(MANIFEST_DOCS_TABLE, "End", end);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Chainlog", chainlog);
        _writeTableRow(MANIFEST_DOCS_TABLE, "GemJoin WETH-A", gemJoin);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Pip (DSValue)", pip);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 10,');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, '  "lineage": "multi-root-safe-harbor-plain-new",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase10_Sky.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "vat", vat, false);
        _writeJsonAddr(path, "dai", dai, false);
        _writeJsonAddr(path, "daiJoin", daiJoin, false);
        _writeJsonAddr(path, "jug", jug, false);
        _writeJsonAddr(path, "pot", pot, false);
        _writeJsonAddr(path, "spotter", spotter, false);
        _writeJsonAddr(path, "vow", vow, false);
        _writeJsonAddr(path, "dog", dog, false);
        _writeJsonAddr(path, "flapper", flapper, false);
        _writeJsonAddr(path, "flopper", flopper, false);
        _writeJsonAddr(path, "end", end, false);
        _writeJsonAddr(path, "chainlog", chainlog, false);
        _writeJsonAddr(path, "gemJoin", gemJoin, false);
        _writeJsonAddr(path, "pip", pip, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
