// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";
import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";

/// @notice Phase 5: bind BC Venus (Compound-style) — never redeploy.
contract Script_BC_Phase5_Compound is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-compound.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-compound.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-5-compound.latest.json";

    address public comptroller;
    address public vUsdc;
    address public vWeth;
    address public vWbtc;
    address public vDai;
    address public vBnb;
    address public vUsdt;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 5 Venus/Compound (bind)";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        comptroller = BC_TESTNET.VENUS_COMPTROLLER;
        vUsdc = BC_TESTNET.VENUS_VUSDC;
        vWeth = BC_TESTNET.VENUS_VWETH;
        vWbtc = BC_TESTNET.VENUS_VWBTC;
        vDai = BC_TESTNET.VENUS_VDAI;
        vBnb = BC_TESTNET.VENUS_VBNB;
        vUsdt = BC_TESTNET.VENUS_VUSDT;

        _requireCode(comptroller, "VENUS_COMPTROLLER");
        _requireCode(vUsdc, "VENUS_VUSDC");
        _requireCode(vWeth, "VENUS_VWETH");

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("Phase 5 Venus bind complete (no CREATE3)");
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase5_Compound -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "Comptroller", comptroller);
        _writeTableRow(MANIFEST_DOCS_TABLE, "vUSDC", vUsdc);
        _writeTableRow(MANIFEST_DOCS_TABLE, "vWETH", vWeth);
        _writeTableRow(MANIFEST_DOCS_TABLE, "vWBTC", vWbtc);
        _writeTableRow(MANIFEST_DOCS_TABLE, "vDAI", vDai);
        _writeTableRow(MANIFEST_DOCS_TABLE, "vBNB", vBnb);
        _writeTableRow(MANIFEST_DOCS_TABLE, "vUSDT", vUsdt);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 5,');
        vm.writeLine(path, '  "mode": "bind-only",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase5_Compound.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "comptroller", comptroller, false);
        _writeJsonAddr(path, "vUsdc", vUsdc, false);
        _writeJsonAddr(path, "vWeth", vWeth, false);
        _writeJsonAddr(path, "vWbtc", vWbtc, false);
        _writeJsonAddr(path, "vDai", vDai, false);
        _writeJsonAddr(path, "vBnb", vBnb, false);
        _writeJsonAddr(path, "vUsdt", vUsdt, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
