// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcLiquityPhase9Deploy} from "./BcLiquityPhase9Deploy.sol";

/// @notice Phase 9: Liquity BOLD full WETH collateral branch on BattleChain greenfield.
/// @dev Local/fork only until Tier D. Deploy path lives in BcLiquityPhase9Deploy (testable helper).
contract Script_BC_Phase9_Liquity is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-liquity.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-liquity.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-9-liquity.latest.json";
    string internal constant MANIFEST_RUNTIME_GREENFIELD =
        "script/output/battlechain-sepolia/greenfield-phase9-liquity.latest.json";

    address public phase9Deployer;
    address public boldToken;
    address public addressesRegistry;
    address public borrowerOperations;
    address public troveManager;
    address public priceFeed;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 9 Liquity BOLD";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        // Phase 1 CREATE3 is not required for BOLD CREATE2 branch graph; bind WETH/oracle from BC constants.
        // Prefer Phase 1 bind when constants are filled (post live Phase 1); otherwise WETH from BC_TESTNET only.
        if (BC_TESTNET.CREATE3_FACTORY != address(0) && BC_TESTNET.CREATE3_FACTORY != ABANDONED_CREATE3_FACTORY) {
            _bindPhase1FromConstants();
        }

        address wethAddr = BC_TESTNET.WETH;
        address ethUsd = BC_TESTNET.CHAINLINK_ETH_USD;
        _requireCode(wethAddr, "BC WETH");
        _requireCode(ethUsd, "BC CHAINLINK_ETH_USD");

        BcLiquityPhase9Deploy helper = new BcLiquityPhase9Deploy();
        phase9Deployer = address(helper);
        BcLiquityPhase9Deploy.DeployResult memory r = helper.deployWethBranch(wethAddr, ethUsd);
        boldToken = address(r.boldToken);
        addressesRegistry = address(r.addressesRegistry);
        borrowerOperations = address(r.borrowerOperations);
        troveManager = address(r.troveManager);
        priceFeed = address(r.priceFeed);

        _writeManifest(deployer, r);
        vm.stopBroadcast();

        console2.log("phase9Deployer", phase9Deployer);
        console2.log("boldToken", address(r.boldToken));
        console2.log("addressesRegistry", address(r.addressesRegistry));
        console2.log("borrowerOperations", address(r.borrowerOperations));
        console2.log("troveManager", address(r.troveManager));
        console2.log("priceFeed", address(r.priceFeed));
        console2.log("collateralRegistry", address(r.collateralRegistry));
        console2.log("BC WETH", wethAddr);
        console2.log("BC ETH/USD", ethUsd);
        console2.log("MIN_DEBT = 2000e18 BOLD; openTrove also needs ETH_GAS_COMPENSATION WETH (0.0375e18)");
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    function _writeManifest(address deployer, BcLiquityPhase9Deploy.DeployResult memory r) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer, r);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer, r);
        _writeJson(MANIFEST_RUNTIME_GREENFIELD, deployer, r);

        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase9_Liquity (greenfield) -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "phase9Deployer", phase9Deployer);
        _writeTableRow(MANIFEST_DOCS_TABLE, "BoldToken", address(r.boldToken));
        _writeTableRow(MANIFEST_DOCS_TABLE, "CollateralRegistry", address(r.collateralRegistry));
        _writeTableRow(MANIFEST_DOCS_TABLE, "AddressesRegistry", address(r.addressesRegistry));
        _writeTableRow(MANIFEST_DOCS_TABLE, "ActivePool", address(r.activePool));
        _writeTableRow(MANIFEST_DOCS_TABLE, "DefaultPool", address(r.defaultPool));
        _writeTableRow(MANIFEST_DOCS_TABLE, "GasPool", r.gasPool);
        _writeTableRow(MANIFEST_DOCS_TABLE, "CollSurplusPool", address(r.collSurplusPool));
        _writeTableRow(MANIFEST_DOCS_TABLE, "StabilityPool", address(r.stabilityPool));
        _writeTableRow(MANIFEST_DOCS_TABLE, "SortedTroves", address(r.sortedTroves));
        _writeTableRow(MANIFEST_DOCS_TABLE, "TroveManager", address(r.troveManager));
        _writeTableRow(MANIFEST_DOCS_TABLE, "TroveNFT", address(r.troveNFT));
        _writeTableRow(MANIFEST_DOCS_TABLE, "MetadataNFT", address(r.metadataNFT));
        _writeTableRow(MANIFEST_DOCS_TABLE, "BorrowerOperations", address(r.borrowerOperations));
        _writeTableRow(MANIFEST_DOCS_TABLE, "PriceFeed", address(r.priceFeed));
        _writeTableRow(MANIFEST_DOCS_TABLE, "InterestRouter", address(r.interestRouter));
        _writeTableRow(MANIFEST_DOCS_TABLE, "HintHelpers", address(r.hintHelpers));
        _writeTableRow(MANIFEST_DOCS_TABLE, "MultiTroveGetter", address(r.multiTroveGetter));
        _writeTableRow(MANIFEST_DOCS_TABLE, "RedemptionHelper", address(r.redemptionHelper));
        _writeTableRow(MANIFEST_DOCS_TABLE, "DebtInFrontHelper", address(r.debtInFrontHelper));
        _writeTableRow(MANIFEST_DOCS_TABLE, "WETH", address(r.weth));
        _writeTableRow(MANIFEST_DOCS_TABLE, "CHAINLINK_ETH_USD", r.ethUsdOracle);
    }

    function _writeJson(string memory path, address deployer, BcLiquityPhase9Deploy.DeployResult memory r)
        internal
    {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 9,');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase9_Liquity.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, string.concat('  "phase9Deployer": "', vm.toString(phase9Deployer), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "boldToken", address(r.boldToken), false);
        _writeJsonAddr(path, "collateralRegistry", address(r.collateralRegistry), false);
        _writeJsonAddr(path, "addressesRegistry", address(r.addressesRegistry), false);
        _writeJsonAddr(path, "activePool", address(r.activePool), false);
        _writeJsonAddr(path, "defaultPool", address(r.defaultPool), false);
        _writeJsonAddr(path, "gasPool", r.gasPool, false);
        _writeJsonAddr(path, "collSurplusPool", address(r.collSurplusPool), false);
        _writeJsonAddr(path, "stabilityPool", address(r.stabilityPool), false);
        _writeJsonAddr(path, "sortedTroves", address(r.sortedTroves), false);
        _writeJsonAddr(path, "troveManager", address(r.troveManager), false);
        _writeJsonAddr(path, "troveNFT", address(r.troveNFT), false);
        _writeJsonAddr(path, "metadataNFT", address(r.metadataNFT), false);
        _writeJsonAddr(path, "borrowerOperations", address(r.borrowerOperations), false);
        _writeJsonAddr(path, "priceFeed", address(r.priceFeed), false);
        _writeJsonAddr(path, "interestRouter", address(r.interestRouter), false);
        _writeJsonAddr(path, "hintHelpers", address(r.hintHelpers), false);
        _writeJsonAddr(path, "multiTroveGetter", address(r.multiTroveGetter), false);
        _writeJsonAddr(path, "redemptionHelper", address(r.redemptionHelper), false);
        _writeJsonAddr(path, "debtInFrontHelper", address(r.debtInFrontHelper), false);
        _writeJsonAddr(path, "weth", address(r.weth), false);
        _writeJsonAddr(path, "chainlinkEthUsd", r.ethUsdOracle, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
