// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";
import {Create2Utils} from
    "@crane/contracts/protocols/lending/aave/v4/deployments/utils/libraries/Create2Utils.sol";
import {SpokeBytecodeLinker} from
    "@crane/contracts/protocols/lending/aave/v4/deployments/utils/libraries/SpokeBytecodeLinker.sol";
import {OrchestrationReports} from
    "@crane/contracts/protocols/lending/aave/v4/deployments/libraries/OrchestrationReports.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcAavePhase3Deploy} from "./BcAavePhase3Deploy.sol";

/// @notice Phase 3: Aave V3 market (initReserves) + Aave V4 core + configure (hardcoded).
/// @dev Path B CREATE2: real Safe-compatible factory via BattleChainDeployer (no vm.etch).
///      LiquidationLogic linked at runtime. Phase 1 bind optional for Aave.
///      Fork tests call BcAavePhase3Deploy directly.
contract Script_BC_Phase3_Aave is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-aave.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-aave.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-3-aave.latest.json";

    address public poolAddressesProvider;
    address public poolProxy;
    address public accessManager;
    address public hub;
    address public spoke;
    address public liquidationLogic;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 3 Aave V3+V4";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        // Prefer greenfield bind when Phase 1 constants are set; otherwise skip (Aave does not need Create3).
        if (BC_TESTNET.CREATE3_FACTORY != address(0)) {
            _bindPhase1FromConstants();
        }

        // --- Aave V3 full market ---
        BcAavePhase3Deploy.V3DeployResult memory v3 = BcAavePhase3Deploy.deployV3Market(deployer);
        poolAddressesProvider = v3.report.poolAddressesProvider;
        poolProxy = v3.report.poolProxy;

        // --- Aave V4 core + configure ---
        BcAavePhase3Deploy.V4DeployResult memory v4 = BcAavePhase3Deploy.deployV4Core(deployer);
        BcAavePhase3Deploy.configureV4Market(deployer, v4);
        accessManager = v4.accessManager;
        hub = v4.hub;
        spoke = v4.spoke;
        liquidationLogic = v4.liquidationLogic;

        _writeManifest(deployer, v3, v4);
        vm.stopBroadcast();

        console2.log("poolAddressesProvider", poolAddressesProvider);
        console2.log("accessManager", accessManager);
        console2.log("hub", hub);
        console2.log("spoke", spoke);
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    function _writeManifest(
        address deployer,
        BcAavePhase3Deploy.V3DeployResult memory v3,
        BcAavePhase3Deploy.V4DeployResult memory v4
    ) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer, v3, v4);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer, v3, v4);
        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase3_Aave -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "V3 PoolAddressesProvider", v3.report.poolAddressesProvider);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V3 PoolProxy", v3.report.poolProxy);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V3 AaveOracle", v3.report.aaveOracle);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V4 AccessManager", v4.accessManager);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V4 Hub", v4.hub);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V4 Spoke", v4.spoke);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V4 AaveOracle", v4.aaveOracle);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V4 LiquidationLogic", v4.liquidationLogic);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V4 CREATE2 factory", Create2Utils.getFactory());
    }

    function _writeJson(
        string memory path,
        address deployer,
        BcAavePhase3Deploy.V3DeployResult memory v3,
        BcAavePhase3Deploy.V4DeployResult memory v4
    ) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 3,');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase3_Aave.s.sol",');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "poolAddressesProvider", v3.report.poolAddressesProvider, false);
        _writeJsonAddr(path, "poolProxy", v3.report.poolProxy, false);
        _writeJsonAddr(path, "v3AaveOracle", v3.report.aaveOracle, false);
        _writeJsonAddr(path, "accessManager", v4.accessManager, false);
        _writeJsonAddr(path, "hub", v4.hub, false);
        _writeJsonAddr(path, "spoke", v4.spoke, false);
        _writeJsonAddr(path, "v4AaveOracle", v4.aaveOracle, false);
        _writeJsonAddr(path, "liquidationLogic", v4.liquidationLogic, false);
        _writeJsonAddr(path, "treasurySpoke", v4.treasurySpoke, false);
        _writeJsonAddr(path, "nativeTokenGateway", v4.nativeTokenGateway, false);
        _writeJsonAddr(path, "signatureGateway", v4.signatureGateway, false);
        _writeJsonAddr(path, "create2Factory", Create2Utils.getFactory(), true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
