// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcUniswapPhase7Deploy} from "./BcUniswapPhase7Deploy.sol";

/// @notice Phase 7: Uniswap V4 periphery + concrete V4Router; bind BC Uni V3 (never redeploy V3).
contract Script_BC_Phase7_Uniswap is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-uniswap.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-uniswap.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-7-uniswap.latest.json";
    string internal constant MANIFEST_RUNTIME_GREENFIELD =
        "script/output/battlechain-sepolia/greenfield-phase7-uniswap.latest.json";

    address public phase7Deployer;
    address public uniV3Factory;
    address public uniV3SwapRouter;
    address public uniV3Npm;
    address public uniV4PoolManager;
    address public positionDescriptor;
    address public positionManager;
    address public v4Router;
    address public stateView;
    address public v4Quoter;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 7 Uniswap";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        uniV3Factory = BC_TESTNET.UNISWAP_V3_FACTORY;
        uniV3SwapRouter = BC_TESTNET.UNISWAP_V3_SWAP_ROUTER;
        uniV3Npm = BC_TESTNET.UNISWAP_V3_NFT_POSITION_MANAGER;
        uniV4PoolManager = BC_TESTNET.UNISWAP_V4_POOL_MANAGER;
        address permit2_ = BC_TESTNET.BETTER_PERMIT2;
        address weth_ = BC_TESTNET.WETH;

        if (BC_TESTNET.CREATE3_FACTORY != address(0) && BC_TESTNET.CREATE3_FACTORY != ABANDONED_CREATE3_FACTORY) {
            _bindPhase1FromConstants();
            uniV4PoolManager = BC_TESTNET.UNISWAP_V4_POOL_MANAGER;
            permit2_ = permit2;
            weth_ = weth;
        }

        _requireCode(uniV3Factory, "UNISWAP_V3_FACTORY");
        _requireCode(uniV4PoolManager, "UNISWAP_V4_POOL_MANAGER");
        _requireCode(permit2_, "PERMIT2");

        BcUniswapPhase7Deploy helper = new BcUniswapPhase7Deploy();
        phase7Deployer = address(helper);
        BcUniswapPhase7Deploy.DeployResult memory r =
            helper.deployPeriphery(uniV4PoolManager, permit2_, weth_, uniV3Factory);
        _store(r);

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("phase7Deployer", phase7Deployer);
        console2.log("positionManager", positionManager);
        console2.log("v4Router", v4Router);
        console2.log("stateView", stateView);
        console2.log("v4Quoter", v4Quoter);
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    /// @notice In-process hermetic deploy for tests (own PoolManager + Permit2).
    function deployForHermetic(address owner) external returns (BcUniswapPhase7Deploy.DeployResult memory r) {
        BcUniswapPhase7Deploy helper = new BcUniswapPhase7Deploy();
        phase7Deployer = address(helper);
        r = helper.deployHermetic(owner);
        _store(r);
    }

    function _store(BcUniswapPhase7Deploy.DeployResult memory r) internal {
        uniV4PoolManager = r.poolManager;
        positionDescriptor = r.positionDescriptor;
        positionManager = r.positionManager;
        v4Router = r.v4Router;
        stateView = r.stateView;
        v4Quoter = r.v4Quoter;
        if (r.uniV3Factory != address(0)) uniV3Factory = r.uniV3Factory;
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_GREENFIELD, deployer);
        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase7_Uniswap (greenfield) -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "Uni V3 Factory (BC)", uniV3Factory);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Uni V4 PoolManager", uniV4PoolManager);
        _writeTableRow(MANIFEST_DOCS_TABLE, "PositionDescriptor", positionDescriptor);
        _writeTableRow(MANIFEST_DOCS_TABLE, "PositionManager", positionManager);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V4Router (BcV4Router)", v4Router);
        _writeTableRow(MANIFEST_DOCS_TABLE, "StateView", stateView);
        _writeTableRow(MANIFEST_DOCS_TABLE, "V4Quoter", v4Quoter);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 7,');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase7_Uniswap.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "uniV3Factory", uniV3Factory, false);
        _writeJsonAddr(path, "uniV4PoolManager", uniV4PoolManager, false);
        _writeJsonAddr(path, "positionDescriptor", positionDescriptor, false);
        _writeJsonAddr(path, "positionManager", positionManager, false);
        _writeJsonAddr(path, "v4Router", v4Router, false);
        _writeJsonAddr(path, "stateView", stateView, false);
        _writeJsonAddr(path, "v4Quoter", v4Quoter, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
