// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcAerodromePhase6Deploy} from "./BcAerodromePhase6Deploy.sol";

/// @notice Phase 6: Aerodrome ve(3,3) + Slipstream (governors + fee modules).
/// @dev Deploy path in BcAerodromePhase6Deploy. CLGauge path waived (not in port tree).
contract Script_BC_Phase6_Aerodrome is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-aerodrome.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-aerodrome.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-6-aerodrome.latest.json";
    string internal constant MANIFEST_RUNTIME_GREENFIELD =
        "script/output/battlechain-sepolia/greenfield-phase6-aerodrome.latest.json";

    address public phase6Deployer;
    address public aero;
    address public poolFactory;
    address public voter;
    address public router;
    address public minter;
    address public protocolGovernor;
    address public epochGovernor;
    address public clFactory;
    address public customSwapFeeModule;
    address public customUnstakedFeeModule;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 6 Aerodrome+Slipstream";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        address wethAddr = BC_TESTNET.WETH;
        if (BC_TESTNET.CREATE3_FACTORY != address(0) && BC_TESTNET.CREATE3_FACTORY != ABANDONED_CREATE3_FACTORY) {
            _bindPhase1FromConstants();
            wethAddr = weth;
        }
        _requireCode(wethAddr, "WETH");

        BcAerodromePhase6Deploy helper = new BcAerodromePhase6Deploy();
        phase6Deployer = address(helper);
        BcAerodromePhase6Deploy.DeployResult memory r = helper.deploy(deployer, wethAddr);
        _store(r);

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("phase6Deployer", phase6Deployer);
        console2.log("aero", aero);
        console2.log("protocolGovernor", protocolGovernor);
        console2.log("epochGovernor", epochGovernor);
        console2.log("clFactory", clFactory);
        console2.log("customSwapFeeModule", customSwapFeeModule);
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    /// @notice In-process hermetic deploy for tests.
    function deployForHermetic(address team) external returns (BcAerodromePhase6Deploy.DeployResult memory r) {
        BcAerodromePhase6Deploy helper = new BcAerodromePhase6Deploy();
        phase6Deployer = address(helper);
        r = helper.deployHermetic(team);
        _store(r);
    }

    function _store(BcAerodromePhase6Deploy.DeployResult memory r) internal {
        aero = r.aero;
        poolFactory = r.poolFactory;
        voter = r.voter;
        router = r.router;
        minter = r.minter;
        protocolGovernor = r.protocolGovernor;
        epochGovernor = r.epochGovernor;
        clFactory = r.clFactory;
        customSwapFeeModule = r.customSwapFeeModule;
        customUnstakedFeeModule = r.customUnstakedFeeModule;
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_GREENFIELD, deployer);
        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase6_Aerodrome (greenfield) -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "phase6Deployer", phase6Deployer);
        _writeTableRow(MANIFEST_DOCS_TABLE, "AERO", aero);
        _writeTableRow(MANIFEST_DOCS_TABLE, "PoolFactory", poolFactory);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Voter", voter);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Router", router);
        _writeTableRow(MANIFEST_DOCS_TABLE, "Minter", minter);
        _writeTableRow(MANIFEST_DOCS_TABLE, "ProtocolGovernor", protocolGovernor);
        _writeTableRow(MANIFEST_DOCS_TABLE, "EpochGovernor", epochGovernor);
        _writeTableRow(MANIFEST_DOCS_TABLE, "CLFactory", clFactory);
        _writeTableRow(MANIFEST_DOCS_TABLE, "CustomSwapFeeModule", customSwapFeeModule);
        _writeTableRow(MANIFEST_DOCS_TABLE, "CustomUnstakedFeeModule", customUnstakedFeeModule);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 6,');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase6_Aerodrome.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "phase6Deployer", phase6Deployer, false);
        _writeJsonAddr(path, "aero", aero, false);
        _writeJsonAddr(path, "poolFactory", poolFactory, false);
        _writeJsonAddr(path, "voter", voter, false);
        _writeJsonAddr(path, "router", router, false);
        _writeJsonAddr(path, "minter", minter, false);
        _writeJsonAddr(path, "protocolGovernor", protocolGovernor, false);
        _writeJsonAddr(path, "epochGovernor", epochGovernor, false);
        _writeJsonAddr(path, "clFactory", clFactory, false);
        _writeJsonAddr(path, "customSwapFeeModule", customSwapFeeModule, false);
        _writeJsonAddr(path, "customUnstakedFeeModule", customUnstakedFeeModule, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
