// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";

import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";
import {BcCamelotPhase8Deploy} from "./BcCamelotPhase8Deploy.sol";

/// @notice Phase 8: Camelot V2 factory + router (createPair smoke via helper hermetic).
contract Script_BC_Phase8_Camelot is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-camelot.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-camelot.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-8-camelot.latest.json";
    string internal constant MANIFEST_RUNTIME_GREENFIELD =
        "script/output/battlechain-sepolia/greenfield-phase8-camelot.latest.json";

    address public phase8Deployer;
    address public camelotFactory;
    address public camelotRouter;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 8 Camelot";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        address wethAddr = BC_TESTNET.WETH;
        if (BC_TESTNET.CREATE3_FACTORY != address(0) && BC_TESTNET.CREATE3_FACTORY != ABANDONED_CREATE3_FACTORY) {
            _bindPhase1FromConstants();
            wethAddr = weth;
        }
        _requireCode(wethAddr, "WETH");

        BcCamelotPhase8Deploy helper = new BcCamelotPhase8Deploy();
        phase8Deployer = address(helper);
        BcCamelotPhase8Deploy.DeployResult memory r = helper.deploy(deployer, wethAddr);
        camelotFactory = r.camelotFactory;
        camelotRouter = r.camelotRouter;

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("phase8Deployer", phase8Deployer);
        console2.log("camelotFactory", camelotFactory);
        console2.log("camelotRouter", camelotRouter);
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    function deployForHermetic(address feeToSetter)
        external
        returns (BcCamelotPhase8Deploy.DeployResult memory r)
    {
        BcCamelotPhase8Deploy helper = new BcCamelotPhase8Deploy();
        phase8Deployer = address(helper);
        r = helper.deployHermetic(feeToSetter);
        camelotFactory = r.camelotFactory;
        camelotRouter = r.camelotRouter;
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_GREENFIELD, deployer);
        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase8_Camelot (greenfield) -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "CamelotFactory", camelotFactory);
        _writeTableRow(MANIFEST_DOCS_TABLE, "CamelotRouter", camelotRouter);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 8,');
        vm.writeLine(path, '  "generation": "greenfield",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase8_Camelot.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "camelotFactory", camelotFactory, false);
        _writeJsonAddr(path, "camelotRouter", camelotRouter, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
