// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

import {console2} from "forge-std/console2.sol";

import {BC_TESTNET} from "@crane/contracts/constants/networks/BC_TESTNET.sol";
import {BCPhaseScriptBase} from "./BCPhaseScriptBase.s.sol";

/// @notice Phase 4: bind BC mock Euler V2 (EVC + vaults) — never redeploy.
contract Script_BC_Phase4_Euler is BCPhaseScriptBase {
    string internal constant MANIFEST_DOCS_JSON = "docs/deployment/addresses/battlechain-sepolia-euler.json";
    string internal constant MANIFEST_DOCS_TABLE = "docs/deployment/addresses/battlechain-sepolia-euler.table.md";
    string internal constant MANIFEST_RUNTIME_JSON = "script/output/battlechain-sepolia/phase-4-euler.latest.json";

    address public evc;
    address public eUsdc;
    address public eWeth;

    function _protocolName() internal pure override returns (string memory) {
        return "Crane BC Phase 4 Euler (bind)";
    }

    function run() external {
        vm.startBroadcast();
        address deployer = msg.sender;
        _requireNotFoundryDefaultSender(deployer);

        evc = BC_TESTNET.EULER_EVC;
        eUsdc = BC_TESTNET.EULER_EUSDC;
        eWeth = BC_TESTNET.EULER_EWETH;

        _requireCode(evc, "EULER_EVC");
        _requireCode(eUsdc, "EULER_EUSDC");
        _requireCode(eWeth, "EULER_EWETH");

        _writeManifest(deployer);
        vm.stopBroadcast();

        console2.log("Phase 4 Euler bind complete (no CREATE3)");
        console2.log("EVC", evc);
        console2.log("eUSDC", eUsdc);
        console2.log("eWETH", eWeth);
        _logDocsHandoff(MANIFEST_DOCS_JSON, MANIFEST_DOCS_TABLE, MANIFEST_RUNTIME_JSON);
    }

    function _writeManifest(address deployer) internal {
        _writeJson(MANIFEST_DOCS_JSON, deployer);
        _writeJson(MANIFEST_RUNTIME_JSON, deployer);
        vm.writeFile(MANIFEST_DOCS_TABLE, "<!-- GENERATED by Script_BC_Phase4_Euler -->\n");
        vm.writeLine(MANIFEST_DOCS_TABLE, "| Component | Address |");
        vm.writeLine(MANIFEST_DOCS_TABLE, "|-----------|---------|");
        _writeTableRow(MANIFEST_DOCS_TABLE, "EVC (BC mock)", evc);
        _writeTableRow(MANIFEST_DOCS_TABLE, "eUSDC (BC mock)", eUsdc);
        _writeTableRow(MANIFEST_DOCS_TABLE, "eWETH (BC mock)", eWeth);
    }

    function _writeJson(string memory path, address deployer) internal {
        vm.writeFile(path, "{\n");
        vm.writeLine(path, '  "phase": 4,');
        vm.writeLine(path, '  "mode": "bind-only",');
        vm.writeLine(path, '  "script": "scripts/foundry/bc/Script_BC_Phase4_Euler.s.sol",');
        vm.writeLine(path, string.concat('  "deployer": "', vm.toString(deployer), '",'));
        vm.writeLine(path, '  "addresses": {');
        _writeJsonAddr(path, "evc", evc, false);
        _writeJsonAddr(path, "eUsdc", eUsdc, false);
        _writeJsonAddr(path, "eWeth", eWeth, true);
        vm.writeLine(path, "  }");
        vm.writeLine(path, "}");
    }
}
